Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/arriendos-frontend, pull requests merged in 2023-12, with the labels that each got.

#98 refactorización en creacion de tipo de clientes y clientes
  src/hooks/useAuthStore.ts
  src/hooks/useEventStore.ts
  src/models/typeCustomerModel.ts
  src/router/AppRouter.tsx
  src/store/customers/customerSlice.ts
  src/store/events/eventSlice.ts
  src/store/extraHours/extraHourSlice.ts
  src/store/hourRanges/hourRangeSlice.ts
  src/store/payments/paymentSlice.ts
  src/store/plans/planSlice.ts
  src/store/products/productSlice.ts
  src/store/properties/propertieSlice.ts
  src/store/rates/rateSlice.ts
  src/store/rentals/rentalSlice.ts
  src/store/requirements/requirementSlice.ts
  src/store/rooms/roomSlice.ts
  src/store/store.ts
  src/store/typesCustomers/typeCustomerSlice.ts
  src/store/users/userSlice.ts
  src/store/warrantys/warrantySlice.ts
  src/utils/menu.tsx
  src/utils/menuSettings.tsx
  src/views/auth/AuthPage.tsx
  src/views/pages/customers/contact/CardContact.tsx
  src/views/pages/customers/contact/Phone.tsx
  src/views/pages/customers/createCustomer/CreateCustomer.tsx
  src/views/pages/typesCustomers/CreateTypeCustomer.tsx
  src/views/pages/typesCustomers/TypeCustomerTable.tsx
Labels: refactoring

#100 agregando tiempo de duración del token
  package.json
  src/services/coffeApi.ts
  src/views/pages/properties/CreatePropertie.tsx
  src/views/pages/properties/DepartamentTable.tsx
Labels: enhancement

#110 realizando validaciones para números
  src/hooks/useForm.ts
  src/views/pages/customers/contact/CardContact.tsx
  src/views/pages/customers/contact/Phone.tsx
  src/views/pages/products/CreateProduct.tsx
Labels: refactoring

#112 estado de carga en tablas
  src/components/Skeleton.tsx
  src/components/index.ts
  src/hooks/useCustomerStore.ts
  src/hooks/useForm.ts
  src/hooks/usePropertieStore.ts
  src/models/productModel.ts
  src/models/propertieModel.ts
  src/store/customers/customerSlice.ts
  src/store/hourRanges/hourRangeSlice.ts
  src/store/products/productSlice.ts
  src/store/properties/propertieSlice.ts
  src/store/rates/rateSlice.ts
  src/store/requirements/requirementSlice.ts
  src/store/typesCustomers/typeCustomerSlice.ts
  src/store/users/userSlice.ts
  src/views/pages/customers/CustomerTable.tsx
  src/views/pages/customers/contact/CardContact.tsx
  src/views/pages/customers/createCustomer/CreateCustomer.tsx
  src/views/pages/hourRanges/CreateHourRange.tsx
  src/views/pages/hourRanges/HourRangeTable.tsx
  src/views/pages/products/CreateProduct.tsx
  src/views/pages/products/ProductTable.tsx
  src/views/pages/products/ProductsView.tsx
  src/views/pages/properties/CreatePropertie.tsx
  src/views/pages/properties/DepartamentTable.tsx
  src/views/pages/properties/PropertieTable.tsx
  src/views/pages/properties/rooms/CreateRoom.tsx
  src/views/pages/properties/rooms/RoomTable.tsx
  src/views/pages/rates/RateTable.tsx
  src/views/pages/requirements/CreateRequirement.tsx
  src/views/pages/requirements/RequirementTable.tsx
  src/views/pages/typesCustomers/CreateTypeCustomer.tsx
  src/views/pages/typesCustomers/TypeCustomerTable.tsx
  src/views/pages/users/UserTable.tsx
Labels: refactoring

#114 correccion en cambio de hora y fecha
  package.json
  src/App.tsx
  src/components/Date.tsx
  src/hooks/useCustomerStore.ts
  src/hooks/useForm.ts
  src/hooks/useHourRangeStore.ts
  src/hooks/useLeasesStates.ts
  src/hooks/useProductStore.ts
  src/hooks/usePropertieStore.ts
  src/hooks/useRateStore.ts
  src/hooks/useRentalStore.ts
  src/hooks/useRequirementStore.ts
  src/hooks/useRoomStore.ts
  src/hooks/useTypeCustomerStore.ts
  src/hooks/useUserStore.ts
  src/store/rentals/rentalSlice.ts
  src/views/pages/customers/contact/CardContact.tsx
  src/views/pages/customers/createCustomer/CreateCustomer.tsx
  src/views/pages/hourRanges/CreateHourRange.tsx
  src/views/pages/products/CreateProduct.tsx
  src/views/pages/properties/CreatePropertie.tsx
  src/views/pages/properties/rooms/CreateRoom.tsx
  src/views/pages/rates/CreateRate.tsx
  src/views/pages/rentalCalendar/RentalCalendarView.tsx
  src/views/pages/rentalCalendar/RentalSection.tsx
  src/views/pages/rentalCalendar/calendar/Calendar.tsx
  src/views/pages/rentalCalendar/stateRental/EventDialog.tsx
  src/views/pages/rentalCalendar/stateRental/InfoRental.tsx
  src/views/pages/rentalCalendar/stateRental/RentalCard.tsx
  src/views/pages/rentalCalendar/stateRental/payments/Main.tsx
  src/views/pages/requirements/CreateRequirement.tsx
  src/views/pages/typesCustomers/CreateTypeCustomer.tsx
  src/views/pages/users/CreateUser.tsx
  yarn.lock
Labels: refactoring

#116 correccion en creacion de evento en el mismo día
  src/components/Date.tsx
  src/helpers/formatDate.ts
  src/views/pages/customers/CustomerTable.tsx
  src/views/pages/customers/contact/ContactTable.tsx
  src/views/pages/hourRanges/HourRangeTable.tsx
  src/views/pages/products/ProductTable.tsx
  src/views/pages/properties/DepartamentTable.tsx
  src/views/pages/properties/rooms/RoomTable.tsx
  src/views/pages/properties/rooms/SubEnviromentTable.tsx
  src/views/pages/rates/RateTable.tsx
  src/views/pages/rentalCalendar/stateRental/EventDialog.tsx
  src/views/pages/rentalCalendar/stateRental/concluded/Main.tsx
  src/views/pages/rentalCalendar/stateRental/reserve/Main.tsx
  src/views/pages/requirements/RequirementTable.tsx
  src/views/pages/typesCustomers/TypeCustomerTable.tsx
  src/views/pages/users/UserLdapTable.tsx
  src/views/pages/users/UserTable.tsx
Labels: refactoring

#118 Arreglandos bugs e implementación de reportes
  src/components/DateRange.tsx
  src/components/styles.css
  src/helpers/formatDate.ts
  src/hooks/useLeasesStates.ts
  src/hooks/useReportStore.ts
  src/models/rentalModel.ts
  src/router/AppRouter.tsx
  src/store/rentals/rentalSlice.ts
  src/utils/menu.tsx
  src/views/pages/rentalCalendar/stateRental/EventDialog.tsx
  src/views/pages/rentalCalendar/stateRental/reserve/Requirement.tsx
  src/views/pages/reports/ReportView.tsx
  src/views/pages/reports/StateTable.tsx
  src/views/pages/reports/index.ts
Labels: bug, enhancement

#120 Arreglando bug de edición de inmueble
  package.json
  src/hooks/useHourRangeStore.ts
  src/hooks/usePropertieStore.ts
Labels: bug, refactoring

#122 opcion todas en paginado
  package.json
  src/components/TablePagination.tsx
  src/hooks/useCustomerStore.ts
  src/hooks/useProductStore.ts
  src/hooks/useRateStore.ts
  src/hooks/useRequirementStore.ts
  src/hooks/useTypeCustomerStore.ts
  src/hooks/useUserStore.ts
  src/views/pages/products/ProductTable.tsx
  src/views/pages/rates/RateTable.tsx
  src/views/pages/requirements/RequirementTable.tsx
  src/views/pages/typesCustomers/TypeCustomerTable.tsx
  src/views/pages/users/UserTable.tsx
Labels: refactoring

#124 Bloqueando horas y minutos antes de la fecha actual para la creación …
  src/components/InputTime.tsx
Labels: refactoring

#126 buscador de producto
  package.json
  src/components/DateRange.tsx
  src/hooks/useProductStore.ts
  src/views/pages/products/ProductTable.tsx
  yarn.lock
Labels: refactoring

#128 arreglando bug de rango de horas
  src/components/InputTime.tsx
  src/hooks/useRentalStore.ts
  src/store/rentals/rentalSlice.ts
  src/views/pages/rentalCalendar/calendar/Calendar.tsx
  yarn.lock
Labels: bug

#130 correción del texto de eliminación
  src/components/Dialog.tsx
  src/components/index.ts
  src/hooks/useCustomerStore.ts
  src/hooks/useExtraHourStore.tsx
  src/hooks/useHourRangeStore.ts
  src/hooks/usePaymentsStore.tsx
  src/hooks/useProductStore.ts
  src/hooks/useRateStore.ts
  src/hooks/useRentalStore.ts
  src/hooks/useRequirementStore.ts
  src/hooks/useTypeCustomerStore.ts
  src/hooks/useUserStore.ts
  src/hooks/useWarrantyStore.tsx
  src/views/pages/products/CreateProduct.tsx
  src/views/pages/rentalCalendar/stateRental/InfoRental.tsx
Labels: refactoring

#132 Modificaciones a los reportes
  src/components/DateWithoutTime.tsx
  src/hooks/useReportStore.ts
  src/views/pages/reports/ReportView.tsx
Labels: refactoring

#135 manejo de estados en el dialog del alquiler
  src/hooks/useLeasesStates.ts
  src/hooks/useRentalStore.ts
  src/hooks/useTypeCustomerStore.ts
  src/models/rentalModel.ts
  src/store/rentals/rentalSlice.ts
  src/utils/createPalette.ts
  src/views/layout/Layout.tsx
  src/views/pages/rentalCalendar/RentalCalendarView.tsx
  src/views/pages/rentalCalendar/cart/CartView.tsx
  src/views/pages/rentalCalendar/stateRental/EventDialog.tsx
  src/views/pages/rentalCalendar/stateRental/InfoRental.tsx
  src/views/pages/rentalCalendar/stateRental/RentalCard.tsx
  src/views/pages/typesCustomers/TypeCustomerTable.tsx
Labels: refactoring

#139 agregando el monto en la creación de una garantía
  src/hooks/useWarrantyStore.tsx
  src/store/warrantys/warrantySlice.ts
  src/views/pages/rental/EditRental.tsx
  src/views/pages/rentalCalendar/stateRental/payments/FormPayments.tsx
  src/views/pages/rentalCalendar/stateRental/payments/Main.tsx
Labels: enhancement

#142 Arreglando recargado en los registros de las subsanaciones
  src/components/Steps.tsx
  src/views/pages/rentalCalendar/stateRental/concluded/Main.tsx
  src/views/pages/rentalCalendar/stateRental/payments/DamageRectify.tsx
  src/views/pages/rentalCalendar/stateRental/payments/FormPayments.tsx
Labels: refactoring

#144 Quitando buscadores de Tarifas y Usuarios y arreglando visualización …
  src/views/pages/customers/CustomerTable.tsx
  src/views/pages/rates/RateTable.tsx
  src/views/pages/users/UserTable.tsx
Labels: bug, refactoring

#146 Modificaciones en la devolución de garantía
  src/hooks/useCustomerStore.ts
  src/views/pages/rental/EditRental.tsx
  src/views/pages/rentalCalendar/stateRental/EventDialog.tsx
  src/views/pages/rentalCalendar/stateRental/InfoRental.tsx
  src/views/pages/rentalCalendar/stateRental/concluded/Main.tsx
Labels: refactoring

#148 Refactorización del menú
  src/utils/menu.tsx
  src/utils/menuSettings.tsx
  src/views/pages/rentalCalendar/calendar/Calendar.tsx
  src/views/pages/rentalCalendar/calendar/styles.css
Labels: refactoring
