Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/arriendos-frontend, pull requests merged in 2023-11, with the labels that each got.

#66 registro de pagos
  src/components/Input.tsx
  src/components/TableContent.tsx
  src/hooks/useForm.ts
  src/hooks/useRentalStore.tsx
  src/models/paymentModel.ts
  src/store/index.ts
  src/store/payments/paymentSlice.ts
  src/store/store.ts
  src/views/pages/products/ProductsView.tsx
  src/views/pages/rentalCalendar/stateRental/EventDialog.tsx
  src/views/pages/rentalCalendar/stateRental/payments/FormPayments.tsx
  src/views/pages/rentalCalendar/stateRental/payments/Main.tsx
  src/views/pages/rentalCalendar/stateRental/payments/Payment.tsx
  src/views/pages/rentalCalendar/stateRental/reserve/Main.tsx
Labels: enhancement

#68 Implementación en frontend de las impresiones de arriendo
  package-lock.json
  package.json
  src/components/Button.tsx
  src/components/Date.tsx
  src/hooks/useRentalStore.tsx
  src/views/pages/rentalCalendar/stateRental/EventDialog.tsx
  src/views/pages/rentalCalendar/stateRental/InfoRental.tsx
  src/views/pages/rentalCalendar/stateRental/concluded/Main.tsx
Labels: enhancement

#70 creacion de hora extra
  src/components/Select.tsx
  src/hooks/index.ts
  src/hooks/useDamageStore.ts
  src/hooks/useExtraHourStore.ts
  src/hooks/useForm.ts
  src/hooks/usePaymentsStore.tsx
  src/hooks/useRentalStore.ts
  src/hooks/useWarrantyStore.ts
  src/models/rentalModel.ts
  src/store/extraHours/extraHourSlice.ts
  src/store/index.ts
  src/store/store.ts
  src/views/pages/rentalCalendar/cart/CartView.tsx
  src/views/pages/rentalCalendar/stateRental/EventDialog.tsx
  src/views/pages/rentalCalendar/stateRental/InfoRental.tsx
  src/views/pages/rentalCalendar/stateRental/payments/ExtraHour.tsx
  src/views/pages/rentalCalendar/stateRental/payments/FormPayments.tsx
  src/views/pages/rentalCalendar/stateRental/payments/Main.tsx
  src/views/pages/rentalCalendar/stateRental/payments/Payment.tsx
  yarn.lock
Labels: enhancement

#71 Implementación de tabla de garantías
  src/hooks/useWarrantyStore.ts
  src/hooks/useWarrantyStore.tsx
  src/store/index.ts
  src/store/store.ts
  src/store/warrantys/warrantySlice.ts
  src/views/pages/rentalCalendar/stateRental/payments/Main.tsx
Labels: enhancement

#73 refactorización en registro de hora extra y daños
  src/components/Select.tsx
  src/hooks/useExtraHourStore.ts
  src/models/rentalModel.ts
  src/views/pages/rentalCalendar/stateRental/payments/Damage.tsx
  src/views/pages/rentalCalendar/stateRental/payments/ExtraHour.tsx
  src/views/pages/rentalCalendar/stateRental/payments/FormPayments.tsx
  src/views/pages/rentalCalendar/stateRental/payments/Main.tsx
Labels: refactoring

#75 refactorización de código
  src/components/Input.tsx
  src/components/TableContent.tsx
  src/hooks/useLeasesStates.ts
  src/hooks/useRentalStore.ts
  src/hooks/useWarrantyStore.tsx
  src/models/paymentModel.ts
  src/views/pages/rentalCalendar/stateRental/EventDialog.tsx
  src/views/pages/rentalCalendar/stateRental/payments/FormPayments.tsx
  src/views/pages/rentalCalendar/stateRental/payments/Main.tsx
  src/views/pages/rentalCalendar/stateRental/payments/Payment.tsx
Labels: refactoring

#77 Agregando doble confirmación en la eliminación de un pago y de una ga…
  src/hooks/usePaymentsStore.tsx
  src/hooks/useWarrantyStore.tsx
Labels: refactoring

#79 Se agregó validaciones en la impresión de documentos e implementación…
  src/hooks/useDamageStore.ts
  src/hooks/useExtraHourStore.tsx
  src/hooks/useLeasesStates.ts
  src/hooks/useRentalStore.ts
  src/views/pages/rentalCalendar/stateRental/payments/Main.tsx
Labels: enhancement

#81 Agregando validación para un tipo de cliente que no tiene tarifas
  src/hooks/useProductStore.ts
Labels: enhancement

#83 Limpiando código para la compilación y dockerizar
  src/components/Button.tsx
  src/helpers/getMessages.ts
  src/hooks/useRoomStore.ts
  src/views/pages/customers/CustomersView.tsx
  src/views/pages/hourRanges/HourRangeView.tsx
  src/views/pages/properties/PropertiesView.tsx
  src/views/pages/properties/rooms/RoomTable.tsx
  src/views/pages/rentalCalendar/stateRental/payments/Main.tsx
  src/views/pages/requirements/RequirementsView.tsx
  src/views/pages/typesCustomers/TypesCustomersView.tsx
  src/views/pages/users/UsersView.tsx
Labels: enhancement

#85 motivo de anulación
  src/components/Date.tsx
  src/hooks/useLeasesStates.ts
  src/hooks/useRentalStore.ts
  src/hooks/useWarrantyStore.tsx
  src/store/index.ts
  src/store/leaseStates/leaseStateSlice.ts
  src/store/rentals/rentalSlice.ts
  src/store/store.ts
  src/views/pages/rentalCalendar/stateRental/EventDialog.tsx
  src/views/pages/rentalCalendar/stateRental/InfoRental.tsx
  src/views/pages/rentalCalendar/stateRental/payments/FormPayments.tsx
  src/views/pages/rentalCalendar/stateRental/payments/Main.tsx
Labels: enhancement

#87 busqueda de clientes
  src/components/Search.tsx
  src/hooks/useCustomerStore.ts
  src/views/pages/customers/CustomerTable.tsx
  src/views/pages/products/ProductTable.tsx
  src/views/pages/rates/RateTable.tsx
  src/views/pages/rental/RentalTable.tsx
  src/views/pages/requirements/RequirementTable.tsx
  src/views/pages/typesCustomers/TypeCustomerTable.tsx
  src/views/pages/users/UserTable.tsx
Labels: enhancement

#89 Modificaciones en los hooks
  src/hooks/useAuthStore.ts
  src/hooks/useCustomerStore.ts
  src/hooks/useDamageStore.ts
  src/hooks/useEventStore.ts
  src/hooks/useExtraHourStore.tsx
  src/hooks/useHourRangeStore.ts
  src/hooks/useLeasesStates.ts
  src/hooks/usePaymentsStore.tsx
  src/hooks/usePlanStore.ts
  src/hooks/useProductStore.ts
  src/hooks/usePropertieStore.ts
  src/hooks/useRateStore.ts
  src/hooks/useRentalStore.ts
  src/hooks/useRequirementStore.ts
  src/hooks/useRoomStore.ts
  src/hooks/useTypeCustomerStore.ts
  src/hooks/useUserStore.ts
  src/hooks/useWarrantyStore.tsx
  src/services/coffeApi.ts
Labels: refactoring

#91 Agregando botón para la devolución de garantía
  src/views/pages/rentalCalendar/stateRental/concluded/Main.tsx
Labels: refactoring

#93 Dockerizando proyecto frontend
  README.md
  dockerfile
  src/helpers/getEnvVariables.ts
  src/hooks/useAuthStore.ts
  src/hooks/useCustomerStore.ts
  src/hooks/useDamageStore.ts
  src/hooks/useEventStore.ts
  src/hooks/useExtraHourStore.tsx
  src/hooks/useHourRangeStore.ts
  src/hooks/useLeasesStates.ts
  src/hooks/usePaymentsStore.tsx
  src/hooks/usePlanStore.ts
  src/hooks/useProductStore.ts
  src/hooks/usePropertieStore.ts
  src/hooks/useRateStore.ts
  src/hooks/useRentalStore.ts
  src/hooks/useRequirementStore.ts
  src/hooks/useRoomStore.ts
  src/hooks/useTypeCustomerStore.ts
  src/hooks/useUserStore.ts
  src/hooks/useWarrantyStore.tsx
  src/services/coffeApi.ts
Labels: documentation, enhancement

#95 autocompletado de datos del afiliado
  .env_example
  README.md
  src/components/Input.tsx
  src/components/Search.tsx
  src/hooks/useAuthStore.ts
  src/hooks/useCustomerStore.ts
  src/models/contactModel.ts
  src/models/propertieModel.ts
  src/models/roomModel.ts
  src/views/auth/AuthPage.tsx
  src/views/pages/customers/contact/CardContact.tsx
  src/views/pages/customers/createCustomer/CreateCustomer.tsx
  src/views/pages/properties/PropertieTable.tsx
  src/views/pages/properties/rooms/RoomTable.tsx
  src/views/pages/properties/rooms/SubEnviromentTable.tsx
Labels: enhancement

#96 Arreglando redirección de rutas
  default.conf
  dockerfile
  yarn.lock
Labels: refactoring
