Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/arriendos-frontend, pull requests merged in 2023-10, with the labels that each got.

#22 creación y edición de requerimientos
  package-lock.json
  src/components/AutoComplete.tsx
  src/components/Button.tsx
  src/components/Input.tsx
  src/components/Search.tsx
  src/components/Select.tsx
  src/components/TablePagination.tsx
  src/components/index.ts
  src/hooks/useRequirementStore.ts
  src/models/index.ts
  src/models/requirementModel.ts
  src/store/index.ts
  src/views/pages/requirements/CreateRequirement.tsx
  src/views/pages/requirements/RequirementTable.tsx
  src/views/pages/requirements/RequirementsView.tsx
Labels: enhancement

#23 eliminación de usuarios
  src/hooks/index.ts
  src/hooks/useUserStore.ts
  src/models/userLdapModel.ts
  src/models/userModel.ts
  src/views/pages/users/CreateUser.tsx
  src/views/pages/users/UserLdapTable.tsx
  src/views/pages/users/UserTable.tsx
  src/views/pages/users/UsersView.tsx
Labels: enhancement

#25 refactorización de tipo de cliente
  src/hooks/useTypeCustomerStore.ts
  src/views/pages/typesCustomers/CreateTypeCustomer.tsx
  src/views/pages/typesCustomers/TypeCustomerTable.tsx
  src/views/pages/typesCustomers/TypesCustomersView.tsx
Labels: bug

#27 creación y asignación de tarifas
  src/hooks/useRateStore.ts
  src/models/rateModel.ts
  src/views/pages/rates/CreateRate.tsx
  src/views/pages/rates/RateTable.tsx
  src/views/pages/rates/RatesView.tsx
Labels: enhancement

#29 refactorización de propiedades e inmuebles
  src/hooks/index.ts
  src/hooks/useRoomStore.ts
  src/store/index.ts
  src/store/rooms/roomSlice.ts
  src/store/store.ts
  src/views/pages/properties/CreatePropertie.tsx
  src/views/pages/properties/PropertieTable.tsx
  src/views/pages/properties/PropertiesView.tsx
  src/views/pages/properties/rooms/RoomTable.tsx
Labels: bug

#31 creacion de productos
  src/hooks/useProductStore.ts
  src/models/days.json
  src/models/productModel.ts
  src/store/products/productSlice.ts
  src/views/pages/products/CreateProduct.tsx
  src/views/pages/products/ProductTable.tsx
  src/views/pages/products/ProductsView.tsx
  src/views/pages/products/index.ts
  src/views/pages/products/products.json
Labels: enhancement

#33 interfaz y creación de rangos de horas
  src/hooks/useHourRangeStore.ts
  src/models/hourRangeModel.ts
  src/store/hourRanges/hourRangeSlice.ts
  src/store/index.ts
  src/views/pages/hourRanges/CreateHourRange.tsx
  src/views/pages/hourRanges/HourRangeTable.tsx
  src/views/pages/hourRanges/HourRangeView.tsx
  src/views/pages/hourRanges/index.ts
Labels: enhancement

#35 refactorizacion en creación de clientes
  package.json
  src/hooks/useForm.ts
  src/models/contactModel.ts
  src/models/customerModel.ts
  src/utils/menu.tsx
  src/views/pages/customers/CreateCustomer.tsx
  src/views/pages/customers/CustomerTable.tsx
  src/views/pages/customers/CustomersView.tsx
  src/views/pages/customers/RowCustomer.tsx
  src/views/pages/customers/contact/ContactTable.tsx
  src/views/pages/customers/contact/CreateContact.tsx
  src/views/pages/customers/contact/index.ts
  src/views/pages/customers/createCustomer/CardContact.tsx
  src/views/pages/customers/createCustomer/CreateCustomer.tsx
  src/views/pages/customers/createCustomer/index.ts
  src/views/pages/customers/createCustomer/styles.css
  src/views/pages/customers/index.ts
  yarn.lock
Labels: bug

#37 refactorización de clientes con contactos
  src/hooks/useCustomerStore.ts
  src/hooks/useForm.ts
  src/hooks/useUserStore.ts
  src/models/contactModel.ts
  src/models/customerModel.ts
  src/views/pages/customers/CustomerTable.tsx
  src/views/pages/customers/CustomersView.tsx
  src/views/pages/customers/RowCustomer.tsx
  src/views/pages/customers/contact/CardContact.tsx
  src/views/pages/customers/contact/ContactTable.tsx
  src/views/pages/customers/contact/CreateContact.tsx
  src/views/pages/customers/contact/index.ts
  src/views/pages/customers/createCustomer/CardContact.tsx
  src/views/pages/customers/createCustomer/CreateCustomer.tsx
  src/views/pages/customers/createCustomer/index.ts
Labels: bug

#41 reafactorización de productos y edicion
  src/hooks/useHourRangeStore.ts
  src/hooks/useProductStore.ts
  src/hooks/usePropertieStore.ts
  src/hooks/useRequirementStore.ts
  src/hooks/useTypeCustomerStore.ts
  src/models/productModel.ts
  src/store/hourRanges/hourRangeSlice.ts
  src/views/pages/hourRanges/CreateHourRange.tsx
  src/views/pages/hourRanges/HourRangeTable.tsx
  src/views/pages/products/CreateProduct.tsx
  src/views/pages/products/ProductTable.tsx
  src/views/pages/properties/PropertieTable.tsx
  src/views/pages/properties/rooms/RoomTable.tsx
  src/views/pages/rates/RateTable.tsx
  src/views/pages/requirements/RequirementTable.tsx
  src/views/pages/typesCustomers/TypeCustomerTable.tsx
Labels: bug, enhancement

#42 Arriendos v1
  package-lock.json
  package.json
  src/components/Button.tsx
  src/components/Input.tsx
  src/components/Select.tsx
  src/hooks/index.ts
  src/hooks/useCustomerStore.ts
  src/hooks/useEventStore.ts
  src/hooks/useProductStore.ts
  src/hooks/useRoomStore.ts
  src/hooks/useSelectedProductStore.ts
  src/hooks/useTypeCustomerStore.ts
  src/models/days.json
  src/models/rentalModel.ts
  src/store/customers/customerSlice.ts
  src/store/events/eventSlice.ts
  src/store/index.ts
  src/store/products/productSlice.ts
  src/store/selectedProducts/productSelectedSlice.ts
  src/store/store.ts
  src/styles.css
  src/views/layout/TopNav.tsx
  src/views/pages/customers/CustomerTable.tsx
  src/views/pages/customers/RowCustomer.tsx
  src/views/pages/products/ProductTable.tsx
  src/views/pages/rental/CartSelectedProduct.tsx
  src/views/pages/rental/RentalView.tsx
  src/views/pages/rental/calendar/Calendar.tsx
  src/views/pages/rental/calendar/styles.css
  yarn.lock
Labels: enhancement

#43 Visualización de eventos en el calendario
  src/hooks/useProductStore.ts
  src/views/pages/rental/CartSelectedProduct.tsx
  src/views/pages/rental/RentalView.tsx
  src/views/pages/rental/calendar/Calendar.tsx
Labels: enhancement

#45 refactorizacion de calendario con componentes
  src/hooks/useProductStore.ts
  src/hooks/usePropertieStore.ts
  src/store/products/productSlice.ts
  src/store/store.ts
  src/views/pages/customers/CustomerTable.tsx
  src/views/pages/customers/RowCustomer.tsx
  src/views/pages/properties/rooms/RoomTable.tsx
  src/views/pages/rental/CartSelectedProduct.tsx
  src/views/pages/rental/RentalCard.tsx
  src/views/pages/rental/RentalView.tsx
  src/views/pages/rental/calendar/Calendar.tsx
  src/views/pages/rental/createRental/CardEvent.tsx
  src/views/pages/rental/createRental/index.ts
  src/views/pages/rental/index.ts
Labels: refactoring

#46 Visualización de eventos por día en la creación de arriendo
  src/hooks/useProductStore.ts
  src/hooks/useRoomStore.ts
  src/views/pages/rental/CartSelectedProduct.tsx
  src/views/pages/rental/RentalCard.tsx
  src/views/pages/rental/RentalView.tsx
  src/views/pages/rental/calendar/Calendar.tsx
Labels: enhancement

#48 creación de arriendo
  src/components/AutoComplete.tsx
  src/components/AutoCompleteSelect.tsx
  src/components/InputTime.tsx
  src/components/index.ts
  src/hooks/useCustomerStore.ts
  src/hooks/useForm.ts
  src/hooks/useHourRangeStore.ts
  src/hooks/useProductStore.ts
  src/hooks/usePropertieStore.ts
  src/hooks/useRateStore.ts
  src/hooks/useRequirementStore.ts
  src/hooks/useTypeCustomerStore.ts
  src/hooks/useUserStore.ts
  src/models/eventModel.ts
  src/models/hourRangeModel.ts
  src/models/index.ts
  src/models/productModel.ts
  src/models/rateModel.ts
  src/views/pages/hourRanges/CreateHourRange.tsx
  src/views/pages/hourRanges/HourRangeTable.tsx
  src/views/pages/products/CreateProduct.tsx
  src/views/pages/products/ProductTable.tsx
  src/views/pages/rates/CreateRate.tsx
  src/views/pages/rates/RateTable.tsx
  src/views/pages/rental/CartSelectedProduct.tsx
  src/views/pages/rental/RentalView.tsx
  src/views/pages/rental/Select.tsx
  src/views/pages/rental/createRental/CardEvent.tsx
Labels: enhancement

#50 creacion de telefonos
  src/components/InputTime.tsx
  src/components/Select.tsx
  src/hooks/index.ts
  src/hooks/useCustomerStore.ts
  src/hooks/useProductStore.ts
  src/hooks/useSelectedProductStore.ts
  src/hooks/useSelectionsStore.ts
  src/models/contactModel.ts
  src/models/eventModel.ts
  src/models/rentalModel.ts
  src/store/customers/customerSlice.ts
  src/store/index.ts
  src/store/products/productSlice.ts
  src/store/selectedProducts/productSelectedSlice.ts
  src/store/selections/selectionSlice.ts
  src/store/store.ts
  src/views/pages/customers/CustomerTable.tsx
  src/views/pages/customers/CustomersView.tsx
  src/views/pages/customers/RowCustomer.tsx
  src/views/pages/customers/contact/CardContact.tsx
  src/views/pages/customers/contact/ContactTable.tsx
  src/views/pages/customers/contact/CreateContact.tsx
  src/views/pages/customers/contact/Phone.tsx
  src/views/pages/customers/contact/index.ts
  src/views/pages/customers/createCustomer/CreateCustomer.tsx
  src/views/pages/customers/index.ts
  src/views/pages/products/ProductsView.tsx
  src/views/pages/rates/RateTable.tsx
  src/views/pages/rental/CartSelectedProduct.tsx
  src/views/pages/rental/RentalCard.tsx
  src/views/pages/rental/RentalSection.tsx
  src/views/pages/rental/RentalView.tsx
  src/views/pages/rental/calendar/Calendar.tsx
  src/views/pages/rental/cart/CardEvent.tsx
  src/views/pages/rental/cart/CartView.tsx
  src/views/pages/rental/cart/Select.tsx
  src/views/pages/rental/cart/index.ts
  src/views/pages/rental/createRental/index.ts
  src/views/pages/rental/index.ts
  src/views/pages/users/CreateUser.tsx
  src/views/pages/users/UserLdapTable.tsx
  src/views/pages/users/UsersView.tsx
Labels: enhancement

#52 refactorización en creación de alquiler
  package.json
  src/components/InputSelect.tsx
  src/components/InputTime.tsx
  src/components/Select.tsx
  src/components/index.ts
  src/hooks/index.ts
  src/hooks/usePlanStore.ts
  src/hooks/useProductStore.ts
  src/hooks/useRateStore.ts
  src/hooks/useRentalStore.ts
  src/models/index.ts
  src/models/planModel.ts
  src/store/index.ts
  src/store/plans/planSlice.ts
  src/store/products/productSlice.ts
  src/store/rentals/rentalSlice.ts
  src/store/store.ts
  src/utils/menu.tsx
  src/utils/menuSettings.tsx
  src/views/layout/Layout.tsx
  src/views/layout/SideNav.tsx
  src/views/pages/customers/CustomerTable.tsx
  src/views/pages/customers/createCustomer/CreateCustomer.tsx
  src/views/pages/products/CreateProduct.tsx
  src/views/pages/products/ProductTable.tsx
  src/views/pages/properties/rooms/RoomTable.tsx
  src/views/pages/rates/CreateRate.tsx
  src/views/pages/rates/RatesView.tsx
  src/views/pages/rental/RentalCard.tsx
  src/views/pages/rental/RentalSection.tsx
  src/views/pages/rental/RentalView.tsx
  src/views/pages/rental/calendar/Calendar.tsx
  src/views/pages/rental/calendar/styles.css
  src/views/pages/rental/cart/CardEvent.tsx
  src/views/pages/rental/cart/CartView.tsx
  src/views/pages/rental/cart/Select.tsx
  src/views/pages/rental/cart/index.ts
  src/views/pages/users/CreateUser.tsx
  yarn.lock
Labels: refactoring

#54 Pasos arriendos
  src/hooks/useLeasesStates.ts
  src/hooks/useRentalStore.ts
  src/store/index.ts
  src/store/leaseStates/leaseStateSlice.ts
  src/store/store.ts
  src/views/pages/rental/RentalCard.tsx
  src/views/pages/rental/calendar/Calendar.tsx
  src/views/pages/rental/createRental/EventDialog.tsx
  src/views/pages/rental/createRental/index.ts
Labels: enhancement

#55 Moviendo componentes
  src/views/pages/rental/RentalSection.tsx
  src/views/pages/rental/createRental/index.ts
  src/views/pages/rental/index.ts
  src/views/pages/rental/stateRental/EventDialog.tsx
  src/views/pages/rental/stateRental/InfoRental.tsx
  src/views/pages/rental/stateRental/RentalCard.tsx
  src/views/pages/rental/stateRental/index.ts
Labels: enhancement

#59 Steps segunda versión
  package.json
  src/hooks/useForm.ts
  src/hooks/useRentalStore.ts
  src/models/paymentModel.ts
  src/views/pages/rental/stateRental/EventDialog.tsx
  src/views/pages/rental/stateRental/paid/PaidContent.tsx
  src/views/pages/rental/stateRental/paid/ProcessContent.tsx
  src/views/pages/rental/stateRental/paid/index.ts
  src/views/pages/rental/stateRental/reserve/Reserve.tsx
  src/views/pages/rental/stateRental/reserve/index.ts
Labels: enhancement

#63 Refactorización en componentes y carpetas diferentes los estados del …
  src/components/TableContent.tsx
  src/hooks/useRentalStore.ts
  src/views/pages/rentalCalendar/stateRental/EventDialog.tsx
  src/views/pages/rentalCalendar/stateRental/InfoRental.tsx
  src/views/pages/rentalCalendar/stateRental/RentalCard.tsx
  src/views/pages/rentalCalendar/stateRental/concluded/Main.tsx
  src/views/pages/rentalCalendar/stateRental/paid/PaidContent.tsx
  src/views/pages/rentalCalendar/stateRental/paid/ProcessContent.tsx
  src/views/pages/rentalCalendar/stateRental/paid/index.ts
  src/views/pages/rentalCalendar/stateRental/payments/Main.tsx
  src/views/pages/rentalCalendar/stateRental/reserve/Main.tsx
  src/views/pages/rentalCalendar/stateRental/reserve/index.ts
Labels: enhancement, refactoring

#64 Impresión de solicitud de devolución de garantía
  src/hooks/useRentalStore.ts
  src/views/pages/rentalCalendar/stateRental/EventDialog.tsx
  src/views/pages/rentalCalendar/stateRental/concluded/Main.tsx
Labels: enhancement
